# .github/workflows/lint.yml
---
name: lint-check
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    name: Lint Check # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Project Dependencies
        run: |
          make install  # create .venv and install dependencies

      - name: Run Ruff Lint Check
        run: |
          make ruff-lint-check  # Check formatting with ruff

      - name: Run YAML Lint Check
        run: |
          make yaml-lint-check  # Check formatting with yamllint

      - name: Run Ansible Lint Check
        run: |
          make ansible-lint-check  # Check formatting with ansible-lint
